CREATE TABLE BaseReportCriteria (
    [BaseReportCriteriaId] INT,
    [Category] NVARCHAR(16),
    [FriendlyField] NVARCHAR(39),
    [Field] NVARCHAR(31)
);
INSERT INTO BaseReportCriteria VALUES
    (1,N'Demographics',N'Demographics - Email',N'Employee.Email'),
    (2,N'Demographics',N'Demographics - First Name',N'Employee.FirstName'),
    (3,N'Demographics',N'Demographics - Last Name',N'Employee.LastName'),
    (4,N'Demographics',N'Demographics - Department',N'Employee.Department'),
    (5,N'Demographics',N'Demographics - Office',N'Employee.Office'),
    (6,N'Demographics',N'Demographics - Primary Industry',N'Employee.PrimaryIndustry'),
    (7,N'Demographics',N'Demographics - Sector',N'Employee.Sector'),
    (8,N'Demographics',N'Demographics - Mandatory Retirement',N'Employee.MandatoryRetirement'),
    (9,N'Demographics',N'Demographics - Gender',N'Employee.Gender'),
    (10,N'Demographics',N'Demographics - Race',N'Employee.Race'),
    (11,N'Demographics',N'Demographics - Direct Admit',N'Employee.DirectAdmit'),
    (12,N'Demographics',N'Demographics - Last Review',N'Employee.LastReview'),
    (13,N'Demographics',N'Demographics - Status',N'Employee.Status'),
    (14,N'Demographics',N'Demographics - Original Hire Date',N'Employee.OriginalHireDate'),
    (15,N'Demographics',N'Demographics - Experience Credit',N'Employee.ExperienceCredit'),
    (16,N'Experience',N'Accounts Served - Account',N'AccountServed.Account'),
    (17,N'Experience',N'Accounts Served - Client Service',N'AccountServed.ClientService'),
    (18,N'Experience',N'Accounts Served - Industry',N'AccountServed.Industry'),
    (19,N'Experience',N'Accounts Served - Sector',N'AccountServed.Sector'),
    (20,N'Experience',N'Accounts Served - Start Date',N'AccountServed.StartDate'),
    (21,N'Experience',N'Accounts Served - End Date',N'AccountServed.EndDate'),
    (22,N'Experience',N'Practice Management - Role',N'PracticeManagement.Role'),
    (23,N'Experience',N'Practice Management - Other',N'PracticeManagement.Other'),
    (24,N'Experience',N'Practice Management - Office',N'PracticeManagement.Office'),
    (25,N'Experience',N'Practice Management - Industry',N'PracticeManagement.Industry'),
    (26,N'Experience',N'Practice Management - Sector',N'PracticeManagement.Sector'),
    (27,N'Experience',N'Practice Management - Start Date',N'PracticeManagement.StartDate'),
    (28,N'Experience',N'Practice Management - End Date',N'PracticeManagement.EndDate'),
    (29,N'Experience',N'Boards and Committees - Board Committee',N'BoardsCommittees.BoardCommittee'),
    (30,N'Experience',N'Boards and Committees - Other',N'BoardsCommittees.Other'),
    (31,N'Experience',N'Boards and Committees - Role',N'BoardsCommittees.Role'),
    (32,N'Career Interests',N'Career Interests - Role',N'CareerInterest.Role'),
    (33,N'Career Interests',N'Career Interests - Other',N'CareerInterest.Other'),
    (34,N'Career Interests',N'Career Interests - Office',N'CareerInterest.Office'),
    (35,N'Career Interests',N'Career Interests - Industry',N'CareerInterest.Industry'),
    (36,N'Career Interests',N'Career Interests - Sector',N'CareerInterest.Sector'),
    (37,N'Career Interests',N'General Areas of Interest - Department',N'GeneralInterest.Department'),
    (38,N'Career Interests',N'Interest In Relocation - Location',N'ReloInterest.Location'),
    (39,N'Career Interests',N'Interest In Relocation - Interest Level',N'ReloInterest.InterestLevel'),
    (40,N'Career Interests',N'Interest In Relocation - Timing',N'ReloInterest.Timing');