create table ReportCriteria (
	ReportCriteriaId INT IDENTITY(1,1) NOT NULL,
	Field VARCHAR(255),
	Operator VARCHAR(255),
	FriendlyWhere VARCHAR(255)
CONSTRAINT [PK_ReportCriteria] PRIMARY KEY CLUSTERED 
(
	[ReportCriteriaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
